export {default as Dashboard} from './Dashboard'
export {default as MainPage} from './MainPage'
export {default as MyProfile} from './MyProfile'
export {default as EditProfile} from './EditProfile'
export {default as Categories} from './Categories'
export {default as ServiceDetailsPage} from './ServiceDetailsPage'
export {default as Cart} from './Cart'